-- Wrap current_setting()/auth.* calls in RLS policy predicates in (select ...) so
-- Postgres evaluates each once per statement (an InitPlan) instead of once per row.
-- Predicate-equivalent (row visibility unchanged). Generated by 'pgrls fix --rule
-- PERF001' and verified on Postgres 16 (PERF001 -> 0).

-- [PERF001] Wrap auth function call(s) in policy 'agents_owner' on public.agents so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY agents_owner ON public.agents
    USING (owner_user_id = CAST((SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'app_users_self' on public.app_users so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY app_users_self ON public.app_users
    USING (id = CAST((SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'run_history_visible' on public.run_history so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY run_history_visible ON public.run_history
    USING (runner_user_id = CAST((SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) AS uuid) OR EXISTS (SELECT 1 FROM agent_versions AS v INNER JOIN agents AS a ON a.id = v.agent_id WHERE v.id = run_history.agent_version_id AND a.owner_user_id = CAST(current_setting(CAST('app.current_user_id' AS text), TRUE) AS uuid)));

-- [PERF001] Wrap auth function call(s) in policy 'spec_drafts_owner' on public.spec_drafts so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY spec_drafts_owner ON public.spec_drafts
    USING (owner_user_id = CAST((SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) AS uuid));

-- [PERF001] Wrap auth function call(s) in policy 'user_settings_owner' on public.user_settings so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY user_settings_owner ON public.user_settings
    USING (owner_user_id = CAST((SELECT current_setting(CAST('app.current_user_id' AS text), TRUE)) AS uuid));
